import React from 'react'

import './globals.css'
import { Header } from '@/components/shared/header/header'

export const metadata = {
  title: 'Template app',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="pt-BR" className="bg-light-yellow px-24 py-8 text-dark-blue">
    <body>
      <Header />
      {children}
    </body>
  </html>
)

export default RootLayout
